### ISSUE TITLE
pytest -v -s script.py not showing any log

### ISSUE THREAD

**Issue by horta** [saltstack/pytest-logging#2]
`py.test -v -s limix_qep/test/test_bernoulli.py`

```
========================================================================= test session starts ==========================================================================
platform darwin -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /Users/horta/anaconda2/bin/python
cachedir: .cache
rootdir: /Users/horta/workspace/limix-qep, inifile:
plugins: logging-2015.11.4
collected 3 items

limix_qep/test/test_bernoulli.py::test_bernoulli_lml PASSED
limix_qep/test/test_bernoulli.py::test_bernoulli_optimize PASSED
limix_qep/test/test_bernoulli.py::test_bernoulli_prediction PASSED

======================================================================= 3 passed in 6.15 seconds =======================================================================
```

Isn't it supposed to show all messages that I have sent from doing:

``` python
import logging
self._logger = logging.getLogger(__name__)
self._logger.debug("Hello mom!")
```

Note: the above code are inside the files that contains the tests but actually inside the files of the package that is being tested. Not sure if that matters. I'm kind of confused o.o

**Comment by s0undt3ch** [comment]
Try passing additional `-v` since you are logging at the debug level.

Also note that this plugin is going to be merged into pytest-catchlog. See #1, https://github.com/eisensheng/pytest-catchlog/pull/20 and https://github.com/eisensheng/pytest-catchlog/pull/33

**Comment by horta** [comment]
But I'm already passing -v.

**Comment by s0undt3ch** [comment]
Yes, I saw, but you need to lower the log level by increasing verbosity, `-vv`,  `-vvv`,  `-vvv`, etc...

**Comment by horta** [comment]
Ops. Thanks a lot!! =) It works now.

**Comment by s0undt3ch** [comment]
:+1:
