### ISSUE TITLE
setup.py tries to read version.py as ascii, contains Unicode

### ISSUE THREAD

**Issue by akaihola** [saltstack/pytest-logging#4]
There's a UTF-8 encoded copyright symbol in `pytest_logging/version.py`.

`setup.py` tries to read the file like:

    with open(os.path.join(SETUP_DIRNAME, 'pytest_logging', 'version.py')) as rfh:

This fails if the OS locale is C or some other non-UTF-8 locale:

    # python3.5 setup.py
    Traceback (most recent call last):
      File "setup.py", line 34, in <module>
        exec(rfh.read(), None, _LOCALS)  # pylint: disable=exec-used
      File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 105: ordinal not in range(128)

I encountered this in a CentOS 7 Docker image.

**Comment by s0undt3ch** [comment]
Please see https://github.com/saltstack/pytest-logging/issues/3#issuecomment-254253564
