### ISSUE TITLE
Locale issues can cause setup.py to fail

### ISSUE THREAD

**Issue by wouterdb** [saltstack/pytest-logging#5]
When running test in containers, I get the following error:

```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-x_ykztu6/pytest-logging/setup.py", line 34, in <module>
exec(rfh.read(), None, _LOCALS) # pylint: disable=exec-used
File "/opt/inmanta/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 105: ordinal not in range(128)
```

This is due `rfh.read()` on line 34 op setup.py. If the default encoding of the locale is not UTF-8 this line fails on the copyright character in the heading of version.py .

It would be better to use `rfh.read(encoding="utf-8")`

**Comment by s0undt3ch** [comment]
Please see https://github.com/saltstack/pytest-logging/issues/3#issuecomment-254253564 and #1
