### ISSUE TITLE
Fill in variables in license?

### ISSUE THREAD

**Issue by tomkinsc** [saltstack/pytest-logging#6]
Over in conda-forge, @synapticarbors has noticed the placeholder values of the license file in this repository [and has requested](https://github.com/conda-forge/staged-recipes/pull/2451#discussion_r101811429) that I open an issue here to ask that the [license file](https://github.com/saltstack/pytest-logging/blob/master/LICENSE) in this repo be completed to fill in variables, like dates and the copyright holder. I'd guess the vast majority of repositories never bother to do this, and I question whether it has legal meaning at all since the license is very clearly associated with a timestamped project of a particular user, but nonetheless I'd like to request that the license be fleshed out so I can hopefully get pytest-logging into conda-forge for distribution.

**Comment by s0undt3ch** [comment]
While I should probably fix this, I'd like to warn you not to include this project in conda, and instead, if not there already, include pytest-catchlog.

This project is only still here to hold the name for pytest-catchlog which will be renamed to pytest-logging.

No bug fixes or feature additions will be made to this project.

**Comment by tomkinsc** [comment]
Thanks for the heads-up! We have a project that uses pytest-logging, so I guess I'll switch it to pytest-catchlog until the rename happens.
